const STORAGE_NAME = "@gameplay";

const COLLECTION_USERS = `${STORAGE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${STORAGE_NAME}:appointments`;

export { COLLECTION_USERS, COLLECTION_APPOINTMENTS };
